test:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes_from:
        - cache
    links:
        - db
    environment:
        NODE_ENV: test

db:
    image: mongo:latest
    hostname: db
    expose: 
        - "27017"

builder:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes_from:
        - cache
    entrypoint: "build.sh"

cache:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes:
        - /tmp/cache:/root/.npm
        - /build
    entrypoint: "true"