test:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes_from:
        - cache
    links:
        - db
    environment:
        NODE_ENV: test
        MOCHA_FILE: ./reports/unit_tests.xml
    entrypoint: "test.sh"
    command: ./node_modules/.bin/mocha --reporter mocha-junit-reporter
    

db:
    image: mongo:latest
    hostname: db
    expose: 
        - "27017"

builder:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes_from:
        - cache
    entrypoint: "build.sh"

cache:
    build: ../../
    dockerfile: docker/dev/Dockerfile
    volumes:
        - /tmp/cache:/root/.npm
        - /build
    entrypoint: "true"