version: 0.0

containers:
    main:
        phases:
            install:
                commands:
                    - echo Starting the Docker service...
                    - echo Nothing to do in the install phase..
                    - apt-get install -y build-essential
                    - apt-get install -y python-pip
                    - pip install docker-compose
            pre_build:
                commands:
                    - echo Entering pre_build phase...
                    - echo Nothing to do in the pre_build phase...
            during_build: 
                commands:
                    - echo Entering during_build phase...
                    - echo Build started on `date`
                    - docker-compose --version
                    - make test
            post_build:
                commands:
                    - echo Build completed on  `date`