app:
    build: ../../
    dockerfile: docker/release/Dockerfile
    links:
        - db
    environment:
        NODE_ENV: production
    ports:
        - "8080:8080"

test:
    image: timdelgado/todobackend-specs
    links:
        - app
    environment:
        URL: http://app:8080/api/todos
        JUNIT_REPORT_PATH: /reports/acceptance.xml
        JUNIT_REPORT_STACK: 1
    command: --reporter mocha-jenkins-reporter

db:
    image: mongo:latest
    hostname: db
    expose: 
        - "27017"